### ISSUE TITLE
APPLICATION ERROR #18

### ISSUE THREAD

**Issue by dm-msk** [mantisbt/dokuwiki-plugin-authmantis#1]
`Toggle sidebar
MantisBT Toggle user menu
APPLICATION ERROR #18

Page redirection error, ensure that there are no spaces outside the PHP block (<?php ?>) in config_inc.php or custom_*.php files.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
Previous non-fatal errors occurred. Page contents follow.`

**Comment by dregad** [comment]
This is a DokuWiki plugin, and you're reporting a MantisBT application error, which doesn't quite make sense in this context.

Please provide detailed, step-by-step instructions to reproduce the problem.
