### ISSUE TITLE
Console errors mantis core.php

### ISSUE THREAD

**Issue by thefyfy** [mantisbt/dokuwiki-plugin-authmantis#2]
Hi,

Got differents errors when I enable this line in my `local.protected.php` : 
`require_once( MANTIS_ROOT . 'core.php' );`

![image](https://user-images.githubusercontent.com/1229018/107404378-83ca9680-6b06-11eb-8303-99ad2113d871.png)

Authentication still works with default dokuwiki template but when I enable bootstrap template, this one cannot display. If I comment `require_once( MANTIS_ROOT . 'core.php' );`, bootstrap display correctly.

Any idea ?

Thanks

**Comment by dregad** [comment]
It looks like the template you're using relies on inline scripts, which is blocked by the Content Security Policy (CSP) that is is set by MantisBT.

You have several options:
- use another, more well-behaved template that does not rely on inline scripts
- modify the template to extract inline scripts and move them to separate .js files (might be a complex undertaking)
- install the [cspheader plugin](https://www.dokuwiki.org/plugin:cspheader) and configure it as appropriate to enable the inline scripts (**not recommended !**)
- Customize or disable MantisBT security policy to allow inline scripts (**not recommended !**)

**Comment by thefyfy** [comment]
Problem is that errors are shown with default template. Not with the custom one (sorry for misconfusion).
And that error disappear if I just comment `require_once( MANTIS_ROOT . 'core.php' );` (of course mantis auth doesn't work anymore when I comment it...)

**Comment by thefyfy** [comment]
I think (and maybe I'm wrong), it's quite the same thing like in your thread [here](https://www.mantisbt.org/bugs/view.php?id=23635#c58877), but I cannot reproduce your config in the current CSPHeader plugin...😕

**Comment by dregad** [comment]
That is for sure the same root cause.

A new release of the cspheader plugin has recently been published, but I have not yet had time to update my instances so I need to check if this requires changes in the config.

**Comment by thefyfy** [comment]
On my side, I confirm that I use the last release from [here](https://www.dokuwiki.org/plugin:cspheader). I'm on a fresh install of DokuWiki started yesterday 😅

**Comment by BattleMage** [comment]
I'm experiencing the same issue. Fresh default installation and followed the instructions for _authmantis_ plugin.
Tried different templates, as suggested by https://github.com/mantisbt/dokuwiki-plugin-authmantis/issues/2#issuecomment-776158950 but all had the same CORS errors.

Had to install csp plugin and define the following settings for **default-src**:

<dl>
  <dt>'self'</dt>
  <dd>Default value</dd>
  <dt>https://www.dokuwiki.org</dt>
  <dd>To show plugin and template images in th econfiguration</dd>
  <dt>https://www.gravatar.com</dt>
  <dd>To show avatars from gravatar</dd>
  <dt>'unsafe-inline'</dt>
  <dd>To have some dokuwiki script executed</dd>
  <dt>'unsafe-inline'</dt>
  <dd>To have some dokuwiki script executed</dd>
  <dt>'unsafe-eval'</dt>
  <dd>To have some dokuwiki script executed</dd>
  <dt>data:</dt>
  <dd>To have some default dokuwiki icons shown</dd>
</dl>

This was unexpected and unpleasant to figure out.

**Comment by dregad** [comment]
@BattleMage thanks for the feedback and sorry for your trouble. 

I believe your CSP configuration is too lax; in particular, and to my knowledge : 

- `unsafe-inline` is only needed for _scripts-src_ and _styles-src_ so you should not put it in default-src
- I don't think `unsafe-eval` is required at all (at least for default template, based on my experience)
- `https://www.dokuwiki.org` and `data:` are only needed for _img-src_

I'll update he documentation.

**Comment by dregad** [comment]
I've added a [_Content Security Policy_ section](https://www.dokuwiki.org/plugin:authmantis#content_security_policy) including suggested configuration in the plugin's documentation. 

I hope this helps.
