### ISSUE TITLE
The authmantis plugin requires MantisBT Core to be loaded in the DokuWiki config file.

### ISSUE THREAD

**Issue by hammerstone18** [mantisbt/dokuwiki-plugin-authmantis#4]
i have some problem when i change aututype to authmantis ,but i dont konw why because the document that i can read is too many years ago,
if i add "require_once( MANTIS_ROOT . 'core.php' );" in "local.php",but after add,i cant  visit dokuwiki via url

**Comment by dregad** [comment]
The installation instructions are here https://www.dokuwiki.org/plugin:authmantis
